insert into tb_state(name,abbreviation) values('Paraná','PR');
insert into tb_state(name,abbreviation) values('Acre','AC');
insert into tb_state(name,abbreviation) values('Alagoas','AL');
insert into tb_state(name,abbreviation) values('Amapá','AP');
insert into tb_state(name,abbreviation) values('Amazonas','AM');
insert into tb_state(name,abbreviation) values('Bahia','BA');
insert into tb_state(name,abbreviation) values('Ceará','CE');
insert into tb_state(name,abbreviation) values('Distrito Federal','DF');
insert into tb_state(name,abbreviation) values('Espírito Santo','ES');
insert into tb_state(name,abbreviation) values('Goiás','GO');
insert into tb_state(name,abbreviation) values('Maranhão','MA');
insert into tb_state(name,abbreviation) values('Mato Grosso','MT');
insert into tb_state(name,abbreviation) values('Mato Grosso do Sul','MS');
insert into tb_state(name,abbreviation) values('Minas Gerais','MG');
insert into tb_state(name,abbreviation) values('Pará','PA');
insert into tb_state(name,abbreviation) values('Paraíba','PB');
insert into tb_state(name,abbreviation) values('Pernambuco','PE');
insert into tb_state(name,abbreviation) values('Piauí','PI');
insert into tb_state(name,abbreviation) values('Rio de Janeiro','RJ');
insert into tb_state(name,abbreviation) values('Rio Grande do Norte','RN');
insert into tb_state(name,abbreviation) values('Rio Grande do Sul','RS');
insert into tb_state(name,abbreviation) values('Rondônia','RO');
insert into tb_state(name,abbreviation) values('Roraima','RR');
insert into tb_state(name,abbreviation) values('Santa Catarina','SC');
insert into tb_state(name,abbreviation) values('São Paulo','SP');
insert into tb_state(name,abbreviation) values('Sergipe','SE');
insert into tb_state(name,abbreviation) values('Tocantins','TO');